dịch UI và part 1-1
sveltevietnam/learn.svelte.dev pull request #2
Opened 2023-10-10 06:34 UTC by sorae42

Những thứ đã dịch:
- Giao diện người dùng
- Phần 1 - Introduction
- Mình dịch cả tutorial và vài string bên editor luôn

Mình cũng có thay đổi một số asset (dùng logo của Svelte Vietnam) trong này.

2023-10-10 15:52 UTC, vnphanquang requested changes
Cảm ơn @sorae42 👏🏼. Bước đầu rất khả quan. Mình chỉ có vài feedback đơn giản nhé

2023-10-10 15:52 UTC, vnphanquang commented on README.md
> +### _Dưới đây là `README.md` gốc:_
Để gọn gàng mình đề xuất bỏ đường dẫn tới README gốc và xóa hết bản gốc ở đây nhé @sorae42

2023-10-10 15:52 UTC, vnphanquang commented on content/tutorial/01-svelte/01-introduction/01-welcome-to-svelte/README.md
> +> Bản dịch tiếng Việt hiện tại chưa được hoàn chỉnh, nếu có vấn đề thì bạn nên mở issue [tại đây](https://github.com/sveltevietnam/learn.svelte.dev/issues).
@sorae42 thêm marker để có gì sau này mình track lại cho dễ nhé

```suggestion
<!-- TODO: remove when appropriate -->
> Bản dịch tiếng Việt hiện tại chưa được hoàn chỉnh, nếu có vấn đề thì bạn nên mở issue [tại đây](https://github.com/sveltevietnam/learn.svelte.dev/issues).
```

2023-10-10 15:52 UTC, vnphanquang commented on content/tutorial/01-svelte/01-introduction/04-styling/README.md
> +title: Định dạng
Chữ styling mình không rõ dịch chuẩn là gì, nhưng định dạng nghe sẽ khó hình dung đc ý nghĩa. Trong trường hợp này (hoặc tương tự), mình có thể thêm từ gốc trong ngoặc để giúp người đọc dễ nhận biết từ khóa nhé.
```suggestion
title: Định dạng (Styling)
```

2023-10-10 15:52 UTC, vnphanquang commented on content/tutorial/01-svelte/01-introduction/06-html-tags/README.md
> +> **LƯU Ý!** Svelte không khử các biểu thức _(expression)_ bên trong `{@html ...}` trước khi nó được chèn vào trong _DOM_. Đây không hẵn là vấn đề nếu nội dung là những thứ mà bạn có thể tin cậy như
Thêm từ khóa gốc, lý do như trên

```suggestion
> **LƯU Ý!** Svelte không khử các biểu thức _(expression)_ bên trong `{@html ...}` trước khi nó được chèn vào trong _DOM_. Đây không hẵn là vấn đề nếu nội dung là những thứ mà bạn có thể tin cậy như một bài báo mà bạn tự viết. Tuy nhiên, nếu nó là nội dung do người dùng viết mà không tin cậy, ví dụ như một bình luận trên bài báo, thì việc khử các biểu thức là điều rất quan trọng, còn không thì người dùng của bạn sẽ bị dính phải những cuộc tấn công liên quan tới  <a href="https://owasp.org/www-community/attacks/xss/" target="_blank">Tập lệnh chéo trang (Cross-Site Scripting)</a> (XSS).
```

2023-10-10 15:52 UTC, vnphanquang commented on content/tutorial/common/static/favicon.png
Mình không khuyến khích đổi logo ở đây lắm, vì các nội dung này vẫn thuộc quyền sở hữu của team Svelte, chúng ta chỉ đơn thuần đi dịch thôi. Người ta sẽ không kiện mình đâu, nhưng mình nên thể hiện sự tôn trọng và giữ tài nguyên gốc nhiều nhất có thể nhé.

2023-10-10 15:52 UTC, vnphanquang commented on src/routes/+error.svelte
> +			<a href="https://github.com/sveltevietnam/sveltevietnam.dev/issues">GitHub</a>.
```suggestion
			<a href="https://github.com/sveltevietnam/learn.svelte.dev/issues">GitHub</a>.
```

2023-10-10 15:52 UTC, vnphanquang commented on static/sveltevietnam-logo.png
xóa này nhé, lý do như trên

2023-10-10 15:52 UTC, vnphanquang commented on static/sveltevietnam-logo.svg
xóa này nhé, lý do như trên

2023-10-10 16:16 UTC, sorae42 commented
Logo thì mình sẽ xoá bên mình rồi tạo pr sau nha

2023-10-11 01:58 UTC, vnphanquang approved these changes
fixes provided in next PR in https://github.com/sveltevietnam/learn.svelte.dev/pull/3

2023-10-11 01:58 UTC, merged