Đã dịch xong phần 1-2
sveltevietnam/learn.svelte.dev pull request #3
Opened 2023-10-10 16:56 UTC by sorae42

2023-10-10 16:57 UTC, sorae42 commented on content/tutorial/01-svelte/02-reactivity/meta.json
> +	"title": "Tính phản ứng (Reactivity)",
mình nên để nguyên xi "Reactivity" hay dịch luôn cả cụm này và để từ khoá bên cạnh nhỉ?

2023-10-11 02:03 UTC, vnphanquang commented
@sorae42 giúp mình `rebase` với `sveltevietnam:main` nhé

2023-10-11 03:19 UTC, vnphanquang requested changes
Một số comment nhỏ nhé @sorae42 :pray:

2023-10-11 03:19 UTC, vnphanquang commented on content/tutorial/01-svelte/02-reactivity/02-reactive-declarations/README.md
> +> Đừng lo nếu cái này nhìn lạ với bạn. Nó là JavaScript [hợp lệ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label) (nếu không theo truyền thống), tức Svelte sẽ xem n
bạn dịch rất sát nghĩa nhưng mình nghĩ sẽ hơi khó hiểu. Đề xuất sửa một tí như sau:

```suggestion
> Đừng lo nếu cái này nhìn lạ với bạn. Nó là JavaScript [hợp lệ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label) (nhưng không quá phổ biến), tức Svelte sẽ xem nó như 'chạy lại code này mỗi khi bất kì giá trị nào được nêu có sự thay đổi'. Một khi bạn đã quen nó thì sẽ không muốn dùng thứ khác đâu.
```

2023-10-11 03:19 UTC, vnphanquang commented on content/tutorial/01-svelte/02-reactivity/meta.json
> +	"title": "Tính phản ứng (Reactivity)",
Tạm thời hãy giữ nguyên hoặc thêm từ `reactive` và `reactivity` @sorae42 nhé, vì đây là từ khóa quan trọng mà mình nghĩ từ dịch `phản ứng` chưa truyền tải đầy đủ lắm. Có thể ta sẽ quay lại sửa sau khi tìm ra từ thích hợp.

2023-10-11 03:19 UTC, vnphanquang commented on content/tutorial/01-svelte/02-reactivity/04-updating-arrays-and-objects/README.md
> +...sẽ không kích hoạt tính phản ứng với `obj.foo.bar`, trừ khi bạn tiếp nối với `obj = obj`.
```suggestion
...sẽ không kích hoạt tính phản ứng (reactivity) với `obj.foo.bar`, trừ khi bạn tiếp nối với `obj = obj`.
```

2023-10-11 03:19 UTC, vnphanquang commented on content/tutorial/01-svelte/02-reactivity/04-updating-arrays-and-objects/README.md
> +Vì tính phản ứng của Svelte chỉ được kích hoạt bởi phép gán, sử dụng những phương thức như `push` hay `splice` thì sẽ không xảy ra việc cập nhật tự động. Ví dụ như khi bạn bấm vào nút 'Thêm một số' t
```suggestion
Vì tính phản ứng (reactivity) của Svelte chỉ được kích hoạt bởi phép gán, sử dụng những phương thức như `push` hay `splice` thì sẽ không xảy ra việc cập nhật tự động. Ví dụ như khi bạn bấm vào nút 'Thêm một số' thì sẽ không có chuyện gì xảy ra, mặc dù chúng ta đang gọi `numbers.push(...)` ở bên trong `addNumber`.
```

2023-10-11 03:19 UTC, vnphanquang commented on content/tutorial/01-svelte/02-reactivity/02-reactive-declarations/README.md
> +Tất nhiên, bạn có thể ghi đơn giản là `{count * 2}` trong cái markup - bạn không cần phải sử dụng giá trị phản ứng. Giá trị phản ứng sẽ trở nên có giá trị (không phải chơi chữ) khi bạn cần tham chiếu
```suggestion
Tất nhiên, bạn có thể ghi đơn giản là `{count * 2}` trong cái markup - bạn không cần phải sử dụng giá trị phản ứng (reactive values). Giá trị phản ứng sẽ trở nên có giá trị (không phải chơi chữ) khi bạn cần tham chiếu nó nhiều lần, hoặc bạn có giá trị mà phải dựa trên những giá trị phản ứng _khác_.
```

2023-10-11 03:19 UTC, vnphanquang commented on content/tutorial/01-svelte/02-reactivity/03-reactive-statements/README.md
> +Chúng ta không chỉ giới hạn việc khai báo _giá trị_ phản ứng - ta cũng có thể chạy bất kì _câu lệnh_ nào một cách phản ứng. Ví dụ như ta có thể ghi nhật kí giá trị của `count` mỗi khi nó thay đổi.
```suggestion
Chúng ta không chỉ giới hạn việc khai báo _giá trị_ phản ứng (reactive values) - ta cũng có thể chạy bất kì _câu lệnh_ nào một cách phản ứng. Ví dụ như ta có thể ghi nhật kí giá trị của `count` mỗi khi nó thay đổi.
```

2023-10-11 03:32 UTC, merged