Dịch xong 1-4. Logic
sveltevietnam/learn.svelte.dev pull request #50
Opened 2023-10-11 16:50 UTC by sorae42

2023-10-12 17:56 UTC, sorae42 commented
mình bỏ qua cái `dynamic attribute` ạ, cái commit đó chỉ fix typo một từ nên cũng không đáng tạo thêm một branch mới ạ

2023-10-12 17:57 UTC, sorae42 commented on content/tutorial/01-svelte/01-introduction/03-dynamic-attributes/README.md
sửa typo, bỏ qua file này.

2023-10-13 13:56 UTC, vnphanquang requested changes
@sorae42 như cũ, có một vài comment theo ý kiến chủ quan. Thảo luận thêm nếu cần nhé

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/01-if-blocks/README.md
> +HTML không có cách nào để diễn đạt _logic_, như điều kiện và vòng lặp. Nhưng Svelte thì có.
```suggestion
HTML không thể để diễn đạt logic như điều kiện hay vòng lặp. Nhưng Svelte thì làm được.
```

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/01-if-blocks/README.md
> +Để cho ra những markup có điều kiện, chúng ta sẽ bao nó trong một khối `if`. Sau đó ta hãy thêm vài chữ khi `count` lớn hơn `10`:
```suggestion
Để hiển thị có điều kiện một đoạn markup, ta bao nó trong một khối `if`. Như bên dưới, ta hiện thị một cụm từ chỉ khi biến `count` lớn hơn `10`:
```

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/01-if-blocks/README.md
> +Thử đi - sửa lại component, và bấm nút.
```suggestion
Hãy thử sửa lại component và sau đó nhấn nút.
```

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/02-else-blocks/README.md
> +Cũng như trong JavaScript, một khối `if` cũng sẽ có khối `else`:
```suggestion
Cũng như trong JavaScript, một khối `if` có thể có khối `else` theo sau:
```

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/02-else-blocks/README.md
> +> Kí tự `#` luôn dùng để chỉ định khi _mở một khối_. Còn kí tự `#` luôn dùng để chỉ định khi _đóng một khối_. Kí tự `:`, như trong `{:else}`, sẽ dùng để chỉ định những _khối tiếp diễn_. Đừng lo - bạn
```suggestion
> Kí tự `#` luôn dùng để chỉ định khi _mở một khối_. Còn kí tự `/` luôn dùng để chỉ định khi _đóng một khối_. Kí tự `:`, như trong `{:else}`, sẽ dùng để chỉ định những _khối tiếp diễn_. Đừng lo, so với tất cả cú pháp mà Svelte thêm vào HTML, bạn vừa học gần hết rồi.
```

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/04-each-blocks/README.md
> +Khi xây dựng giao diện người dùng, bạn sẽ phải làm việc với những danh sách dữ liệu. Trong bài này, chúng ta đã viết markup `<button>` nhiều lần - mỗi lần thay đổi một màu - nhưng ta vẫn còn nhiều cá
Ở đây người ta dùng list vơi ý như array trong lập trình, nên mình nghĩ từ "mảng" sẽ phù hợp hơn là "danh sách".

Đoạn này:

> In this exercise, we've repeated the `<button>` markup multiple times — changing the colour each time — but there's still more to add.

Đọc tiếng Anh còn khó hiểu, nên mình đã thay đổi cách hành văn hy vọng dễ hiểu hơn.

```suggestion
Khi xây dựng giao diện người dùng, bạn sẽ phải làm việc với mảng dữ liệu. Trong bài này, markup `<button>` được lặp lại nhiều lần, mỗi lần một màu, nhưng vẫn chưa hiển thị đủ tất cả các màu.
```

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/05-keyed-each-blocks/README.md
> +Mặc định rằng khi bạn thay đổi giá trị của một khối `each`, nó sẽ thêm và xoá giá trị ở _cuối_ mảng, và cập nhật những giá trị mà có thể đã được thay đổi. Nhưng có thể bạn không thích kiểu thế.
```suggestion
Khi bạn thay đổi giá trị của một khối `each`, nó mặc định sẽ thêm và xoá giá trị ở _cuối_ mảng, và cập nhật những giá trị mà có thể đã được thay đổi. Nhưng có thể bạn không muốn vậy.
```

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/05-keyed-each-blocks/README.md
> +> Bạn có thể dùng bất kì đối tượng nào làm khoá, vì Svelte sử dụng `Map` ở bên trong - cách nói khác là bạn có thể dùng `(thing)` thay cho `(thing.id)`. Dùng dải kí tự hoặc số sẽ an toàn hơn, bởi lẽ
Đoạn này referential equality ý muốn nói tránh viêc dùng JS object làm key vì có thể sẽ bị rerender nhiều lần thậm chí dù content của object ko đổi, vì so sánh object thì là by reference, còn primitive như string hay number thì là by value.

Mình sửa lại để dễ hiểu hơn.

 
```suggestion
> Bạn có thể dùng bất kì đối tượng nào làm khoá, vì Svelte sử dụng `Map` ở bên trong - cách nói khác là bạn có thể dùng `(thing)` thay cho `(thing.id)`. Tuy nhiên dùng dải kí tự hoặc số sẽ an toàn hơn vì giá trị của chúng là không đổi, còn object thì có thể khác (dù dữ liệu vẫn giữ nguyên) vì nó là tham chiếu (reference).
```

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/06-await-blocks/README.md
> +Nhiều ứng dụng web sẽ phải làm việc với dữ liệu không được đồng bộ _(asynchronous, viết tắt: async)_. Svelte giúp bạn _đợi_ _(await)_ giá trị dữ liệu của [promises](https://developer.mozilla.org/en-U
chắc là ko cần dịch promise luôn @sorae42 nhỉ?

```suggestion
Nhiều ứng dụng web sẽ phải làm việc với dữ liệu không được đồng bộ _(asynchronous, viết tắt: async)_. Svelte giúp bạn _đợi_ _(await)_ giá trị dữ liệu của [promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises) vào thẳng trong markup một cách dễ dàng:
```

2023-10-13 13:56 UTC, vnphanquang commented on content/tutorial/01-svelte/04-logic/06-await-blocks/README.md
> +Nếu bạn chắc rằng promise của bạn không thể từ chối, bạn có thể bỏ khối `catch`. Bạn cũng có thể bỏ luôn khối đầu nếu bạn không muốn hiện gì cho đến khi promise được giải quyết:
`reject` là một từ khóa quan trọng trong khái niệm Promise nên mình nghĩ nên giữ nguyên

```suggestion
Nếu bạn chắc rằng promise của bạn không reject (từ chối), có thể bỏ khối `catch`. Bạn cũng có thể bỏ luôn khối đầu nếu bạn không muốn hiện gì cho đến khi promise được giải quyết:
```

2023-10-13 14:56 UTC, merged