docs: 23-dịch-3-basic-sveltekit-routing
sveltevietnam/learn.svelte.dev pull request #57
Opened 2023-10-12 11:31 UTC by tymon3568

2023-10-12 17:29 UTC, sorae42 requested changes
mình thấy có nhiều chỗ bạn dịch sát nghĩa quá nên nhiều câu không được tự nhiên, mình có chỉnh trong suggestion, bạn xem thử

2023-10-12 17:29 UTC, tobedecided0601 commented on content/tutorial/03-sveltekit/02-routing/01-pages/app-a/src/routes/+page.svelte
> +<p>Đây là trang Home.</p>
```suggestion
<p>Đây là Trang chủ.</p>
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/01-pages/README.md
> +title: Pages (Các trang)
```suggestion
title: Pages (Trang)
```

mình không cần để từ chỉ định số lượng ở đây nha, để cho tiêu đề nó ngắn chút

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/03-params/README.md
> +title: Route parameters (Các tham số định tuyến/tham số đường dẫn)
```suggestion
title: Route parameters (Tham số đường dẫn)
```

thế này có vẻ dễ hiểu hơn.

@vnphanquang cảm thấy thế nào?

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/02-layouts/app-b/src/routes/+page.svelte
> +<p>Đây là trang Home.</p>
```suggestion
<p>Đây là Trang chủ.</p>
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/01-pages/README.md
> +SvelteKit sử dụng filesystem-based routing (định tuyến dựa trên hệ thống tệp tin), điều này có nghĩa là khi người dùng điều hướng (truy cập) đến một URL cụ thể của ứng dụng của bạn, thì _routes_ (địn
```suggestion
SvelteKit sử dụng filesystem-based routing _(định tuyến dựa trên hệ thống tệp tin)_, điều này có nghĩa là khi người dùng truy cập đến một URL cụ thể trong ứng dụng của bạn, thì _routes_ trong ứng dụng của bạn — sẽ được xác định bởi các thư mục trong mã nguồn của bạn.
```

mấy chỗ giải thích từ ngữ để trong ngoặc thì để chữ nghiêng cho dễ nhận biết nha.

với lại từ ngữ đã giải thích ở những phần/bài trước thì mình không cần phải giải thích lại nữa chi cho dài dòng.

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/01-pages/README.md
> +Mỗi tệp `+page.svelte` bên trong `src/routes` tạo ra một trang trong ứng dụng của bạn. Trong ứng dụng này, hiện tại chúng ta có một trang — `src/routes/+page.svelte`, tương ứng với đường dẫn `/`. Nếu
```suggestion
Mỗi tệp `+page.svelte` bên trong `src/routes` sẽ tạo ra một trang trong ứng dụng của bạn. Trong ứng dụng này, hiện tại chúng ta có một trang `src/routes/+page.svelte`, tương ứng với đường dẫn `/`. Nếu chúng ta điều hướng đến `/about`, ta sẽ bị lỗi 404 Not Found _(404 Không tìm thấy)_.
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/01-pages/README.md
> +Hãy sửa điều đó. Thêm một trang thứ hai, `src/routes/about/+page.svelte`, sao chép nội dung từ `src/routes/+page.svelte`, và cập nhật nó:
```suggestion
Ta nên giải quyết lỗi đó. Hãy thêm trang thứ hai, `src/routes/about/+page.svelte`, sao chép nội dung từ `src/routes/+page.svelte`, và sửa thành:
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/01-pages/README.md
> +Bây giờ chúng ta có thể navigate (điều hướng) giữa `/` và `/about`.
Mình nên dịch "navigate" thành "chuyển" cho những scenario như này: 
```suggestion
Bây giờ chúng ta có thể chuyển giữa hai trang `/` và `/about`.
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/02-layouts/README.md
> +Các routes (định tuyến) khác nhau của ứng dụng của bạn thường sẽ chia sẻ giao diện người dùng chung. Thay vì lặp lại nó trong mỗi thành phần `+page.svelte`, chúng ta có thể sử dụng một thành phần `+l
```suggestion
Các route khác nhau trong ứng dụng của bạn thường có giao diện giống nhau. Thay vì lặp đi lặp lại trong mỗi component `+page.svelte`, ta nên sử dụng component `+layout.svelte` để áp dụng cho tất cả các route trong chính thư mục đó.
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/02-layouts/README.md
> +Trong ứng dụng này, chúng ta có hai routes, `src/routes/+page.svelte` và `src/routes/about/+page.svelte`, chứa giao diện người dùng điều hướng giống nhau. Hãy tạo một file mới, `src/routes/+layout.sv
```suggestion
Trong ứng dụng này, chúng ta có hai route, `src/routes/+page.svelte` và `src/routes/about/+page.svelte`, chứa thanh điều hướng giống nhau. Vậy nên ta hãy tạo một tệp mới, `src/routes/+layout.svelte`...
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/03-params/README.md
> +Để tạo các routes (định tuyến) với parameters (tham số) động, sử dụng dấu ngoặc vuông xung quanh một tên biến hợp lệ. Ví dụ, một file như `src/routes/blog/[slug]/+page.svelte` sẽ tạo ra một route phù
```suggestion
Để tạo các route với tham số động, ta có thể cho một tên biến vào trong dấu ngoặc vuông. Ví dụ, một tệp như `src/routes/blog/[slug]/+page.svelte` sẽ tạo ra một route phù hợp với `/blog/one`, `/blog/two`, `/blog/three` và nhiều hơn nữa.
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/03-params/README.md
> +Bây giờ chúng ta có thể điều hướng từ trang `/blog` đến các bài viết blog cá nhân. Trong chương tiếp theo, chúng ta sẽ biết cách load (tải) nội dung của chúng.
```suggestion
Bây giờ chúng ta có thể đi từ trang `/blog` đến từng bài blog khác nhau. Trong chương tiếp theo, chúng ta sẽ được học cách load những nội dung đó.
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/03-params/README.md
> +> Nhiều route parameters (tham số định tuyến/ tham số đường dẫn) có thể xuất hiện trong một đoạn URL, miễn là chúng được tách ra bởi ít nhất một ký tự tĩnh:`foo/[bar]x[baz]` là một route hợp lệ trong
```suggestion
> Nhiều route parameters _(tham số đường dẫn)_ có thể xuất hiện trong một đoạn URL, miễn sao chúng được tách ra ít nhất một ký tự: `foo/[bar]x[baz]` là một route hợp lệ trong đó `[bar]` và `[baz]` là các tham số động _(dynamic parameters)_.
```

2023-10-12 17:29 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/02-layouts/README.md
> +Một file `+layout.svelte` áp dụng cho mọi child route (định tuyến con hay rout con), bao gồm cả `+page.svelte` cùng cấp (nếu nó tồn tại). Bạn có thể lồng layouts (các bố cục) theo bất kỳ độ sâu nào.
@vnphanquang "arbitrary depth" nên dịch như thế nào?

2023-10-13 10:09 UTC, tymon3568 commented on content/tutorial/03-sveltekit/02-routing/02-layouts/app-b/src/routes/+page.svelte
> +<p>Đây là trang Home.</p>
Mình nghĩ nên để home để người đọc dể hình dung slug /home, nếu dịch trang chủ luôn thì nên để slug /trang-chu nhé? Ý bạn sao?

2023-10-13 10:35 UTC, sorae42 requested changes

2023-10-13 10:35 UTC, tobedecided0601 commented on content/tutorial/03-sveltekit/02-routing/02-layouts/app-b/src/routes/+page.svelte
> +<p>Đây là trang Home.</p>
Mình có cái h1 hiện là home rồi nên phía dưới mình nên dịch thay vì để nguyên

2023-10-13 10:35 UTC, tobedecided0601 commented on content/tutorial/03-sveltekit/02-routing/03-params/README.md
> +> Nhiều route parameters (tham số định tuyến/ tham số đường dẫn) có thể xuất hiện trong một đoạn URL, miễn là chúng được tách ra bởi ít nhất một ký tự tĩnh:`foo/[bar]x[baz]` là một route hợp lệ trong
mình thì hybrid cả hai, bạn chọn cái nào cũng được hết

2023-10-13 10:37 UTC, sorae42 commented on content/tutorial/03-sveltekit/02-routing/02-layouts/app-b/src/routes/+page.svelte
> +<p>Đây là trang Home.</p>
nếu bạn muốn giữ nguyên thì báo lại mình

2023-10-13 14:33 UTC, vnphanquang commented on content/tutorial/03-sveltekit/02-routing/02-layouts/README.md
> +Một file `+layout.svelte` áp dụng cho mọi child route (định tuyến con hay rout con), bao gồm cả `+page.svelte` cùng cấp (nếu nó tồn tại). Bạn có thể lồng layouts (các bố cục) theo bất kỳ độ sâu nào.
@sorae42 @tymon3568 dịch như vậy ổn rồi. Đoạn này dám cá ông nào không phải người bản địa viết đây.

@tymon3568 sẵn tiện sử rout" thiểu chữ "e" luôn nhé

```suggestion
Một file `+layout.svelte` áp dụng cho mọi child route (định tuyến con hay route con), bao gồm cả `+page.svelte` cùng cấp (nếu nó tồn tại). Bạn có thể lồng layouts (các bố cục) theo bất kỳ độ sâu nào.
```

2023-10-13 14:36 UTC, vnphanquang commented on content/tutorial/03-sveltekit/02-routing/03-params/README.md
> +> Nhiều route parameters (tham số định tuyến/ tham số đường dẫn) có thể xuất hiện trong một đoạn URL, miễn là chúng được tách ra bởi ít nhất một ký tự tĩnh:`foo/[bar]x[baz]` là một route hợp lệ trong
@tymon3568 tùy quyết đinh cái này nhé. Với mình thế này:
- Nếu là từ khóa quan trọng, thì từ khóa đi trước, giải nghĩa trong ngoặc.
- Nếu là từ gốc giữ lại để giải nghĩa rõ, thì giải nghĩa trước, và từ gốc trong ngoặc.

2023-10-13 15:54 UTC, sorae42 approved these changes
lgtm gg

2023-10-13 16:03 UTC, merged