docs: 29-dịch-3-basic-sveltekit-stores
sveltevietnam/learn.svelte.dev pull request #64
Opened 2023-10-23 14:16 UTC by tymon3568

2023-10-26 09:42 UTC, vnphanquang requested changes
Một vài comment

2023-10-26 09:42 UTC, vnphanquang commented on content/tutorial/03-sveltekit/08-stores/01-page-store/README.md
> +title: Trang
Này là tên của store nên mình giữ nguyên nhỉ

```suggestion
title: page
```

2023-10-26 09:42 UTC, vnphanquang commented on content/tutorial/03-sveltekit/08-stores/01-page-store/README.md
> +* `error` — error object của trang hiện tại, nếu có (bạn sẽ tìm hiểu thêm về error handling _(xử lý lỗi)_ trong [bài tập](handleerror) [sau](error-basics))
```suggestion
* `error` — error object của trang hiện tại, nếu có (bạn sẽ tìm hiểu thêm về xử [lý lỗi](handleerror) trong các [bài tập sau](error-basics))
```

2023-10-26 09:42 UTC, vnphanquang commented on content/tutorial/03-sveltekit/08-stores/02-navigating-store/README.md
> +Store `navigating` đại diện cho quá trình điều hướng hiện tại. Khi một quá trình điều hướng bắt đầu — do việc nhấp vào liên kết, hoặc quá trình điều hướng lùi/điều hướng tiến, hoặc một lệnh chuyển tr
```suggestion
Store `navigating` đại diện cho quá trình điều hướng hiện tại. Khi một quá trình điều hướng bắt đầu — do việc nhấp vào liên kết, quá trình điều hướng lùi/tiến, hoặc một lệnh `goto` — giá trị của `navigating` sẽ trở thành một đối tượng với các thuộc tính sau:
```

2023-10-26 09:42 UTC, vnphanquang commented on content/tutorial/03-sveltekit/08-stores/02-navigating-store/README.md
> +- `from` và `to` — các đối tượng với `params`, `route` và thuộc tính `url`
```suggestion
- `from` và `to` — các đối tượng với thuộc tính `params`, `route` và `url`
```

2023-10-26 09:42 UTC, vnphanquang commented on content/tutorial/03-sveltekit/08-stores/02-navigating-store/README.md
> +> Để biết thông tin về type đầy đủ, hãy truy cập tài liệu [`Navigation`](https://kit.svelte.dev/docs/types#public-types-navigation).
```suggestion
> Để biết thông tin đầy đủ về type, hãy truy cập tài liệu [`Navigation`](https://kit.svelte.dev/docs/types#public-types-navigation).
```

2023-10-26 09:42 UTC, vnphanquang commented on content/tutorial/03-sveltekit/08-stores/03-updated-store/README.md
> +Store `updated` chứa `true` hoặc `false` tùy thuộc vào việc một phiên bản mới của ứng dụng đã được deploy hay chưa kể từ khi trang được truy cập lần đầu. Để cho việc này chạy được, `svelte.config.js`
```suggestion
Store `updated` chứa giá trị `true` hoặc `false` tùy thuộc vào việc một phiên bản mới của ứng dụng đã được deploy hay chưa kể từ khi trang được truy cập lần đầu. Để chạy được, `svelte.config.js` của bạn phải chỉ định `kit.version.pollInterval`.
```

2023-10-26 09:42 UTC, vnphanquang commented on content/tutorial/03-sveltekit/08-stores/03-updated-store/app-a/svelte.config.js
> +			// Nên dùng cái tên mang tính deterministic _(chắc chắn, chuẩn xác)_ là tốt nhất
```suggestion
			// Tốt nhất nên dùng giá trị dễ nhận biết
```

2023-10-27 04:17 UTC, tymon3568 commented on content/tutorial/03-sveltekit/08-stores/01-page-store/README.md
> +* `error` — error object của trang hiện tại, nếu có (bạn sẽ tìm hiểu thêm về error handling _(xử lý lỗi)_ trong [bài tập](handleerror) [sau](error-basics))
```suggestion
* `error` — error object của trang hiện tại, nếu có (bạn sẽ tìm hiểu thêm về [xử lý lỗi](handleerror) trong các [bài tập sau](error-basics))
```

2023-10-27 08:33 UTC, merged