docs:30-dịch-3-basic-sveltekit-errors-and-redirects
sveltevietnam/learn.svelte.dev pull request #65
Opened 2023-10-25 09:13 UTC by tymon3568

2023-10-26 10:08 UTC, vnphanquang requested changes
Một vài comment

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/01-error-basics/README.md
> +Khi bạn throw một expected error, bạn đang bảo SvelteKit 'đừng lo, tôi biết tôi đang làm gì ở đây'. Ngược lại, một unexpected error được giả định là một lỗi trong ứng dụng của bạn. Khi một unexpected
```suggestion
Khi bạn throw một lỗi expected, bạn đang bảo SvelteKit 'đừng lo, tôi biết tôi đang làm gì ở đây'. Ngược lại, một lỗi unexpected được giả định là một lỗi trong ứng dụng của bạn. Khi một lỗi unexpected xảy ra, message và stack trace của nó sẽ được ghi vào console.
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/01-error-basics/README.md
> +> Trong chương sau, chúng ta sẽ tìm hiểu về cách thêm xử lý lỗi tùy chỉnh bằng cách sử dụng hook `handleError`.
```suggestion
> Trong chương sau, chúng ta sẽ tìm hiểu về cách sử dụng `handleError` để tùy chỉnh việc xử lý lỗi.
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/01-error-basics/README.md
> +Nếu bạn nhấp vào các liên kết trong ứng dụng này, bạn sẽ nhận thức được một thông báo khác biệt quan trọng: thông điệp expected error được hiển thị cho người dùng, trong khi thông điệp unexpected err
Mình dùng "thông báo" thay cho "thông điệp" vì "thông điệp" nghe có nghĩa tích cực, mình cảm giác không phù hợp lắm.

```suggestion
Nếu bạn nhấp vào các liên kết trong ứng dụng này, bạn sẽ thấy một khác biệt quan trọng: thông báo lỗi expected được hiển thị cho người dùng, trong khi thông báo của lỗi unexpected được thay thế bằng một thông báo tổng quát là 'Internal Error' và một mã trạng thái 500. Đây là vì thông baó lỗi có thể chứa dữ liệu nhạy cảm.
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/02-error-pages/README.md
> +Khi có điều gì đó không đúng bên trong một hàm `load`, SvelteKit sẽ render một trang lỗi.
```suggestion
Khi xảy ra vấn đề trong hàm `load`, SvelteKit sẽ render một trang lỗi.
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/03-fallback-errors/README.md
> +Nếu mọi thứ diễn ra _thực sự_ sai — như một lỗi xảy ra trong khi tải root layout data _(dữ liệu gốc của bố cục)_, hoặc trong khi render trang lỗi — SvelteKit sẽ chuyển sang một trang lỗi tĩnh.
```suggestion
Khi có lỗi xảy ra trong quá trình tải dữ liệu ở root layout hoăc trong khi render trang lỗi - SvelteKit sẽ chuyển sang một trang lỗi tĩnh.
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/03-fallback-errors/README.md
> +- `%sveltekit.error.message%` — thông điệp lỗi
```suggestion
- `%sveltekit.error.message%` — thông báo lỗi
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/README.md
> +Trang lỗi trong bài tập trước đó khá tĩnh. Có thể bạn muốn hiển thị thông báo lỗi để bạn có thể giúp đỡ người dùng nhanh hơn trong kênh hỗ trợ của bạn.
```suggestion
Trang lỗi trong bài tập trước khá tĩnh. Có thể bạn muốn hiển thị thông báo lỗi để giúp người dùng có thể tìm đến các kênh hỗ trợ nhanh hơn.
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/README.md
> +Để tùy chỉnh nó, triển khai hook `handleError` trong `hooks.server.js` và `hooks.client.js`  sẽ chạy khi một unexpected error được throw trong quá trình tải dữ liệu trên server hoặc client tương ứng.
```suggestion
Để tùy chỉnh, triển khai hook `handleError` trong `hooks.server.js` và `hooks.client.js`, được chạy khi một lỗi unexpected xảy ra trong quá trình tải dữ liệu trên server hoặc client.
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/README.md
> +    ---return { message: 'Internal Error' }; // implementation mặc định của hook này---
```suggestion
    ---return { message: 'Internal Error' }; // cấu hình mặc định của hook này---
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/README.md
> +    ---return { message: 'Internal Error' }; // implementation mặc định của hook này---
```suggestion
    ---return { message: 'Internal Error' }; // cấu hình mặc định của hook này---
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/README.md
> +Lưu ý rằng bạn có thể trả về nhiều hơn một thông báo lỗi nếu bạn muốn. Bất kỳ object shape nào bạn trả về sẽ có sẵn trong `$page.error`, yêu cầu duy nhất là có một thuộc tính `message`. Bạn có thể đọ
```suggestion
Lưu ý rằng bạn có thể trả về nhiều hơn một thông báo lỗi nếu bạn muốn. Bất kỳ cấu trúc nào bạn trả về sẽ có sẵn trong `$page.error`, yêu cầu duy nhất là có phải một thuộc tính `message`. Bạn có thể đọc thêm về điều này (và cách thiết lập type-safe!) trong [error docs](https://kit.svelte.dev/docs/errors).
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/README.md
> +> Khi xử lý lỗi, hãy cẩn thận để không giả định rằng đó là một `Error` object, bất cứ thứ gì cũng có thể được throw. Ngoài ra, hãy đảm bảo bạn không để lộ dữ liệu nhạy cảm bằng cách chuyển tiếp quá n
```suggestion
> Khi xử lý lỗi, hãy cẩn thận và không nên giả định rằng đó là một đối tượng `Error` vì bất cứ thứ gì cũng có thể throw được. Ngoài ra, hãy đảm bảo bạn không để lộ dữ liệu nhạy cảm bằng cách chuyển tiếp quá nhiều thông tin.
```

2023-10-26 10:08 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/app-a/src/hooks.server.js
> +	return { message: 'Internal Error' }; // implementation mặc định của hook này
```suggestion
	return { message: 'Internal Error' }; // cấu hình mặc định của hook này
```

2023-10-27 04:29 UTC, tymon3568 commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/app-a/src/hooks.server.js
> +	return { message: 'Internal Error' }; // implementation mặc định của hook này
dùng từ `cấu hình` có chuẩn không @vnphanquang , mình thì cảm nhận nó giống như một hành động hơn, kiểu như ` thực thi `, bắt đầu khởi công một dự án ...

2023-10-27 05:30 UTC, tymon3568 commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/README.md
> +Lưu ý rằng bạn có thể trả về nhiều hơn một thông báo lỗi nếu bạn muốn. Bất kỳ object shape nào bạn trả về sẽ có sẵn trong `$page.error`, yêu cầu duy nhất là có một thuộc tính `message`. Bạn có thể đọ
```suggestion
Lưu ý rằng bạn có thể trả về nhiều hơn một thông báo lỗi nếu bạn muốn. Bất kỳ cấu trúc nào bạn trả về sẽ có sẵn trong `$page.error`, yêu cầu duy nhất là phải có một thuộc tính `message`. Bạn có thể đọc thêm về điều này (và cách thiết lập type-safe!) trong [error docs](https://kit.svelte.dev/docs/errors).
```

2023-10-27 08:41 UTC, vnphanquang commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/app-a/src/hooks.server.js
> +	return { message: 'Internal Error' }; // implementation mặc định của hook này
Hmm, ũng có thể dùng từ "nội dung", hoặc "chi tiết". Mình không rõ phải dịch sát nghĩa từ này sang tiếng Việt như thế nào nhưng nói chung là trong ngữ cảnh này nó chỉ tiết thực hiện của cái hook. @tymon3568 thấy từ nào tự nhiên thì dịch theo vậy nhé :wink:

2023-10-27 16:12 UTC, sorae42 commented on content/tutorial/03-sveltekit/09-errors-and-redirects/xx-custom-error-messages/app-a/src/hooks.server.js
> +	return { message: 'Internal Error' }; // implementation mặc định của hook này
Mình thấy “cấu hình” vẫn được nhé.

2023-10-30 10:27 UTC, merged