Dịch phần 1-5: Events
sveltevietnam/learn.svelte.dev pull request #72
Opened 2023-11-09 18:11 UTC by sorae42

2023-11-15 03:15 UTC, vnphanquang requested changes
@sorae42 good work. Just some comments mostly to keep consistency of the words `event` and `handler`

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/01-dom-events/README.md
> +Như bạn đã thấy, bạn có thể lắng nghe bất kì sự kiện DOM nào trên một phần tử (chẳng hạn như một click chuột hoặc [pointermove](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointermove_ev
```suggestion
Như ta đã thấy, bạn có thể lắng nghe bất kì sự kiện DOM nào trên một phần tử (chẳng hạn như nhấp chuột hoặc [pointermove](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointermove_event)) với `on:`:
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/04-component-events/README.md
> +Component cũng có thể phái _(dispatch)_ các sự kiện. Bạn cần phải tạo một _event dispatcher_ để có thể làm điều này.
```suggestion
Component cũng có thể gởi _(dispatch)_ các sự kiện. Cần tạo một _event dispatcher_ để có thể làm điều này. Hãy sửa lại `Inner.svelte`:
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/04-component-events/README.md
> +> Bạn phải gọi `createEventDispatcher` khi component được khởi tạo lần đầu - bạn không thể chúng gọi sau này, chẳng hạn như trong callback của `setTimeout`. Việc này sẽ liên kết `dispatch` với instan
```suggestion
> Bạn phải gọi `createEventDispatcher` khi component được khởi tạo lần đầu - không thể gọi trễ hơn chẳng hạn như trong callback của `setTimeout`. Việc này sẽ liên kết `dispatch` với thực thể _(instance)_ của component.
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/04-component-events/README.md
> +> Bạn cũng có thể thay đổi tên sự kiện thành thứ khác. Chẳng hạn như thay đổi `dispatch('message', {...})` thành `dispatch('greet', {...})` trong `Inner.svelte` và thay đổi tên attribute từ `on:messa
```suggestion
> Bạn cũng có thể thay đổi tên của sự kiện. Chẳng hạn như thay đổi `dispatch('message', {...})` thành `dispatch('greet', {...})` trong `Inner.svelte` và thay đổi tên thuộc tính từ `on:message` thành `on:greet` trong `App.svelte`.
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/05-event-forwarding/README.md
> +Không như DOM event, component events không _bubble_. Nếu bạn muốn lắng nghe một sự kiện trên component được lồng sâu bên trong, component trung gian đó phải đẩy _(forward)_ sự kiện đó.
```suggestion
<!-- FIXME: Need link for "bubble" -->
Không như sự kiện của DOM, sự kiện từ component không _bubble_. Nếu bạn muốn lắng nghe một sự kiện trên component lồng sâu bên trong, các component trung gian phải chuyển tiếp _(forward)_ sự kiện đó.
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/05-event-forwarding/README.md
> +Trong trường hợp này, chúng ta có `App.svelte` và `Inner.svelte` trong [phần trước](/tutorial/component-events), và bây giờ ta có component `Outer.svelte` bao gồm `<Inner/>`.
```suggestion
Trong trường hợp này, chúng ta có `App.svelte` và `Inner.svelte` trong [phần trước](/tutorial/component-events), và bây giờ ta có component `Outer.svelte` chứa `<Inner/>`.
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/05-event-forwarding/README.md
> +Nhưng bạn phải viết khá nhiều code cho việc này, cho nên Svelte có một cách viết tắt - một event `on:message` mà không có giá trị thì nó có nghĩa là "forward tất cả sự kiện có tên `message`".
```suggestion
Nhưng bạn phải viết khá nhiều code cho việc này, cho nên Svelte có một cách viết tắt - một chỉ thị _(directive)_ `on:message` khi không có giá trị thì nó có nghĩa là "chuyển tiếp tất cả sự kiện có tên `message`".
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/06-dom-event-forwarding/README.md
> +Bạn cũng có thể forward sự kiện cho DOM event luôn.
```suggestion
Bạn cũng có thể chuyển tiếp cả sự kiện của DOM.
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/06-dom-event-forwarding/README.md
> +Để được thông báo khi bấm nút `<BigRedButton>` - ta chỉ cần forward sự kiện `click` trên phần tử `<button>` ở trong `BigRedButton.svelte`:
```suggestion
Để được thông báo khi bấm nút `<BigRedButton>` - ta chỉ cần chuyển tiếp sự kiện `click` trên phần tử `<button>` ở trong `BigRedButton.svelte`:
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/03-event-modifiers/README.md
> +DOM event handler có thể có _modifier_ để thay đổi hành vi của nó. Chẳng hạn như một handler với modifier `once` sẽ làm cho nó chạy đúng _một lần_:
```suggestion
Hàm xử lý sự kiên DOM có thể có _modifier_ để thay đổi hành vi của nó. Chẳng hạn như một hàm xử lý với modifier `once` sẽ làm cho nó chạy đúng _một lần_:
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/03-event-modifiers/README.md
> +- `trusted` - chỉ chạy handler khi `event.isTrusted` là `true`, tức là sự kiện chỉ có thể kích hoạt bởi thao tác từ người dùng thay vì được gọi từ JavaScript bằng `element.dispatchEvent(...)`.
```suggestion
- `preventDefault` — gọi `event.preventDefault()` trước khi chạy hàm xử lý. Hữu ích cho việc xử lý form.
- `stopPropagation` — gọi `event.stopPropagation()`, tránh sự kiện với tới phần tử kế tiếp.
- `passive` - tăng hiệu năng cho việc cuộn trang trên các sự kiện chạm/lăn chuột (Svelte sẽ tự động thêm khi chỗ đó có thể thêm được).
- `nonpassive` — buộc đặt `passive: false`.
- `capture` - chạy hàm xử lý trong giai đoạn [_capture_](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_capture) thay vì giai đoạn [_bubbling_](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling).
- `once` — bỏ kích hoạt hàm xử lý sau khi chạy lần đầu tiên.
- `self` — chỉ chạy hàm xử lý khi `event.target` là phần tử chính nó.
- `trusted` - chỉ chạy hàm xử lý khi `event.isTrusted` là `true`, tức là sự kiện chỉ có thể kích hoạt bởi thao tác từ người dùng thay vì được gọi từ JavaScript bằng `element.dispatchEvent(...)`.
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/02-inline-handlers/README.md
> +> Trong một số framework thường hay có đề xuất nên tránh inline event handler để có hiệu năng tốt nhất, thường là trong các vòng lặp. Lời khuyên đó thì lại không áp dụng cho Svelte - bất kể bạn chọn
```suggestion
> Trong một số framework thường hay có đề xuất nên tránh hàm xử lý cùng dòng để có hiệu năng tốt nhất, đặc biệt là trong các vòng lặp. Lời khuyên đó không áp dụng cho Svelte - bất kể bạn chọn cách nào, trình dịch sẽ luôn làm điều đúng đắn nhất.
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/02-inline-handlers/README.md
> +Bạn cũng có thể khai báo event handler trong cùng một dòng _(inline event handlers)_:
```suggestion
Bạn cũng có thể khai báo hàm xử lý sự kiện cùng dòng:
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/02-inline-handlers/README.md
>  title: Inline handlers
```suggestion
title: Hàm xử lý cùng dòng _(inline handlers)_
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/04-component-events/README.md
> +Sau đó, thêm handler `on:message` vào `App.svelte`:
```suggestion
Sau đó, thêm hàm xử lý `on:message` vào `App.svelte`:
```

2023-11-15 03:15 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/05-event-forwarding/README.md
> +Một cách mà ta _có thể_ giải là thêm `createEventDispatcher` vào `Outer.svelte`, _nghe_ sự kiện `message`, và tạo một handler cho nó:
```suggestion
Một cách mà ta _có thể_ giải là thêm `createEventDispatcher` vào `Outer.svelte`, _nghe_ sự kiện `message`, và tạo một hàm xử lý cho nó:
```

2023-11-16 04:42 UTC, sorae42 commented on content/tutorial/01-svelte/05-events/04-component-events/README.md
> +Component cũng có thể phái _(dispatch)_ các sự kiện. Bạn cần phải tạo một _event dispatcher_ để có thể làm điều này.
Mình nghĩ nên giữ `Bạn cần phải` sẽ được hơn đó ạ.

2023-11-16 04:50 UTC, sorae42 commented on content/tutorial/01-svelte/05-events/04-component-events/README.md
> +> Bạn phải gọi `createEventDispatcher` khi component được khởi tạo lần đầu - bạn không thể chúng gọi sau này, chẳng hạn như trong callback của `setTimeout`. Việc này sẽ liên kết `dispatch` với instan
mình không hiểu tại sao phải dùng "trễ hơn" thay vì "sau này" ạ?

2023-11-16 10:08 UTC, vnphanquang requested changes

2023-11-16 10:08 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/04-component-events/README.md
> +Component cũng có thể phái _(dispatch)_ các sự kiện. Bạn cần phải tạo một _event dispatcher_ để có thể làm điều này.
Ừm, phần đấy mình ko vấn đề @sorae42, quan trọng hơn là từ `dispatch` và phần thiếu thôi nhé (`Update `Inner.svelte`).

P.s, mình tiện sửa "Bạn cần phải" thành "Cần" để giản lượt thôi, tương tự mình sẽ dùng "ta" thay cho "chúng ta", hay những cụm từ tương tự có thể rút gọn và vẫn giữ nguyên ý nghĩa.

2023-11-16 10:08 UTC, vnphanquang commented on content/tutorial/01-svelte/05-events/04-component-events/README.md
> +> Bạn phải gọi `createEventDispatcher` khi component được khởi tạo lần đầu - bạn không thể chúng gọi sau này, chẳng hạn như trong callback của `setTimeout`. Việc này sẽ liên kết `dispatch` với instan
@sorae42 ko khác mấy, bạn có thể giữ nguyên nhưng nhớ bỏ chữ "~~chúng~~" nhé.

2023-11-18 04:02 UTC, vnphanquang approved these changes
LGTM

2023-11-18 04:03 UTC, merged