docs:10-dịch-2-advanced-svelte-motion
sveltevietnam/learn.svelte.dev pull request #73
Opened 2023-11-12 13:50 UTC by tymon3568

2023-11-15 04:37 UTC, vnphanquang requested changes
Good work, just a few very small comments

2023-11-15 04:37 UTC, vnphanquang commented on content/tutorial/02-advanced-svelte/01-motion/01-tweens/README.md
> +Bây giờ, sau khi đã covers những kiến thức cơ bản, là lúc để học một số kỹ thuật Svelte nâng cao, bắt đầu với _motion_.
```suggestion
Sau khi đã đi qua những kiến thức cơ bản, giờ là lúc để ta học đến một số kỹ thuật Svelte nâng cao, bắt đầu với chuyển động _(motion)_.
```

2023-11-15 04:37 UTC, vnphanquang commented on content/tutorial/02-advanced-svelte/01-motion/01-tweens/README.md
> +Việc đặt giá trị và theo dõi cập nhật DOM tự động là tuyệt vời. Bạn biết cái gì còn tuyệt vời hơn không? Làm cho những giá trị đó tween. Svelte bao gồm các công cụ để giúp bạn xây dựng giao diện ngườ
```suggestion
Việc đặt giá trị và theo dõi cập nhật DOM tự động là tuyệt vời. Bạn biết cái gì còn tuyệt vời hơn không? Tween (biến đổi) những giá trị đó. Svelte bao gồm các công cụ để giúp bạn xây dựng giao diện người dùng tuyệt vời sử dụng hoạt hình _(animation)_ để truyền đạt các thay đổi.
```

2023-11-15 04:37 UTC, vnphanquang commented on content/tutorial/02-advanced-svelte/01-motion/01-tweens/README.md
> +- `interpolate` — một hàm `(from, to) => t => value` tùy chỉnh để nội suy giữa các giá trị tùy ý. Theo mặc định, Svelte sẽ nội suy giữa các số, ngày và mảng có hình dạng giống nhau (miễn là chúng chỉ
```suggestion
- `interpolate` — một hàm `(from, to) => t => value` tùy chỉnh để nội suy giữa các giá trị tùy ý. Theo mặc định, Svelte sẽ nội suy giữa các số, ngày, và mảng có hình dạng giống nhau (miễn là chúng chỉ chứa số và ngày hoặc các mảng và đối tượng hợp lệ khác). Ví dụ nếu bạn muốn nội suy các chuỗi màu hoặc ma trận biến đổi, thì hãy cung cấp một hàm nội suy tùy chỉnh
```

2023-11-16 05:03 UTC, tymon3568 commented on content/tutorial/02-advanced-svelte/01-motion/01-tweens/README.md
> +Việc đặt giá trị và theo dõi cập nhật DOM tự động là tuyệt vời. Bạn biết cái gì còn tuyệt vời hơn không? Làm cho những giá trị đó tween. Svelte bao gồm các công cụ để giúp bạn xây dựng giao diện ngườ
```suggestion
Việc đặt giá trị và theo dõi cập nhật DOM tự động là tuyệt vời. Bạn biết cái gì còn tuyệt vời hơn không? Tween (biến đổi) những giá trị đó. Svelte bao gồm các công cụ để giúp bạn xây dựng giao diện người dùng tuyệt vời sử dụng hiệu ứng chuyển động _(animation)_ để truyền đạt các thay đổi.
```

@vnphanquang  animation ở đây là hiệu ứng chuyển động chứ nhĩ?

2023-11-16 10:14 UTC, vnphanquang requested changes

2023-11-16 10:14 UTC, vnphanquang commented on content/tutorial/02-advanced-svelte/01-motion/01-tweens/README.md
> +Việc đặt giá trị và theo dõi cập nhật DOM tự động là tuyệt vời. Bạn biết cái gì còn tuyệt vời hơn không? Làm cho những giá trị đó tween. Svelte bao gồm các công cụ để giúp bạn xây dựng giao diện ngườ
@tymon3568 Mình ok cả hai bạn nhé. "Hoạt" là chuyển động, "hoạt hình" (hay "hoạt họa") là hình chuyển động, nó mang đủ nghĩa và gọn hơn "hiệu ứng chuyển động", nhưng bạn có thể giữ nguyên tùy quyết định nhé

2023-11-17 03:15 UTC, vnphanquang approved these changes

2023-11-17 03:15 UTC, merged