Dịch phần 1-6: Bindings
sveltevietnam/learn.svelte.dev pull request #78
Opened 2023-11-18 01:34 UTC by sorae42

Mấy phần sau dịch hơi bị khó nên nhiều chỗ mình cũng không biết dịch ntn

2023-11-19 02:22 UTC, vnphanquang requested changes
@sorae42 về cơ bản tốt rồi. Mình có suy nghĩ có nên dịch "bind" là "liên kết" không, nhưng chắc là không vì nó là từ khóa trong Svelte, nên giữ nguyên. Vì vậy dịch "binding" là "phép bind" nhé

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/04-select-bindings/README.md
> +title: Bind lựa chọn
Select là `<select>` element, có lẽ ko cần dịch ở đây

```suggestion
title: Bind select
```

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/04-select-bindings/README.md
> +Để ý rằng giá trị của `<option>` là những object thay vì là dải kí tự. Svelte không quan tâm đâu.
```suggestion
Để ý rằng giá trị của `<option>` là đối tượng thay vì là dải kí tự. Svelte không quan tâm đâu.
```

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/04-select-bindings/README.md
> +> Bời vì ta chưa đặt giá trị đầu cho `selected`, phép bind sẽ tự đặt nó thành giá trị mặc định (giá trị đầu tiên trong danh sách). Nhưng bạn phải cẩn trọng — cho đến khi binding được khởi chạy, `sele
```suggestion
> Bời vì ta chưa đặt giá trị đầu cho `selected`, phép bind sẽ tự đặt nó thành giá trị mặc định (giá trị đầu tiên trong danh sách). Nhưng bạn phải cẩn trọng — cho đến khi phép bind được khởi chạy, `selected` sẽ vẫn là _undefined_, nên ta không thể lấy giá trị một cách mù quáng, v.d dùng `selected.id` trong template.
```

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/01-text-inputs/README.md
> +title: Ô nhập văn bản
Mình đề xuất giữ `input` ko cần dịch vì nó chỉ trực tiếp HTML `input`

```suggestion
title: Input văn bản
```

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/02-numeric-inputs/README.md
> +title: Ô nhập số
```suggestion
title: Input số
```

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/03-checkbox-inputs/README.md
> +title: Ô đánh dấu
```suggestion
title: Input đánh dấu
```

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/05-group-inputs/README.md
> +title: Nhóm các ô nhập
```suggestion
title: Nhóm input
```

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/05-group-inputs/README.md
> +Nếu bạn có nhiều ô `type="radio"` hoặc `type="checkbox"` mà liên quan đến cùng một giá trị, bạn có thể dùng `bind:group` cùng với thuộc tính `value`. Các ô đánh dấu _(radio input)_ trong cùng một nhó
```suggestion
Nếu bạn có nhiều ô `type="radio"` hoặc `type="checkbox"` mà liên quan đến cùng một giá trị, bạn có thể dùng `bind:group` cùng với thuộc tính `value`. Các ô đánh dấu _(radio input)_ trong cùng một nhóm sẽ loại trừ lẫn nhau (chỉ được chọn một); ô lựa chọn _(checkbox input)_ trong cùng một nhóm sẽ phân thành một mảng nhiều giá trị.
```

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/06-multiple-select-bindings/README.md
> +title: Chọn nhiều lựa chọn
```suggestion
title: Select chọn nhiều
```

2023-11-19 02:22 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/07-textarea-inputs/README.md
> +Điều này áp dùng cho các binding khác, không chỉ cho các textarea.
```suggestion
Điều này áp dùng cho các phép bind khác, không chỉ textarea.
```

2023-11-20 09:19 UTC, sorae42 commented on content/tutorial/01-svelte/06-bindings/06-multiple-select-bindings/README.md
> +title: Chọn nhiều lựa chọn
Vậy thì mình nghĩ nên dịch thế này
```suggestion
title: Chọn nhiều trong select
```

2023-11-20 10:21 UTC, vnphanquang commented on content/tutorial/01-svelte/06-bindings/06-multiple-select-bindings/README.md
> +title: Chọn nhiều lựa chọn
@sorae42 mình ok nhé

2023-11-21 12:27 UTC, vnphanquang approved these changes
LGTM

2023-11-21 12:27 UTC, merged